# Generated by Django 6.1.1 on 2026-10-03 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.children.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=80)),
                ("middle_name", models.CharField(blank=True, max_length=80)),
                ("last_name", models.CharField(max_length=80)),
                ("preferred_name", models.CharField(blank=True, max_length=80)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("FEMALE", "Girl"),
                            ("MALE", "Boy"),
                            ("UNSPECIFIED", "Unspecified"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Optional. JPEG, PNG, or WebP, up to 5 MB.",
                        upload_to=apps.children.models.child_photo_path,
                        validators=[apps.children.models.validate_child_photo],
                    ),
                ),
                ("address", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("TRANSFERRED", "Transferred"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="schools.schoolclass",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "children",
                "ordering": ["last_name", "first_name"],
                "indexes": [
                    models.Index(
                        fields=["last_name", "first_name"], name="children_ch_last_na_7fe854_idx"
                    ),
                    models.Index(fields=["preferred_name"], name="children_ch_preferr_49dddd_idx"),
                    models.Index(fields=["date_of_birth"], name="children_ch_date_of_8a51a3_idx"),
                    models.Index(fields=["status"], name="children_ch_status_d1a9f1_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["ACTIVE", "INACTIVE", "TRANSFERRED"])),
                        name="child_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("gender__in", ["FEMALE", "MALE", "UNSPECIFIED"])),
                        name="child_gender_valid",
                    ),
                ],
            },
        ),
    ]
