# Generated by Django 6.1.1 on 2026-10-04 18:05

import django.db.models.deletion
from django.db import migrations, models


def seed_age_groups(apps, schema_editor):
    from apps.children.groups import AGE_GROUP_ROWS

    AgeGroup = apps.get_model("children", "AgeGroup")
    for row in AGE_GROUP_ROWS:
        AgeGroup.objects.update_or_create(
            slug=row["slug"],
            defaults={key: value for key, value in row.items() if key not in {"slug", "color"}},
        )


def remove_age_groups(apps, schema_editor):
    AgeGroup = apps.get_model("children", "AgeGroup")
    AgeGroup.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("children", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgeGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=40)),
                (
                    "kind",
                    models.CharField(
                        choices=[("SABBATH", "Sabbath class"), ("YOUTH", "Youth group")],
                        max_length=10,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField()),
                ("min_years", models.PositiveSmallIntegerField()),
                ("max_years", models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["kind", "sort_order"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ["SABBATH", "YOUTH"])),
                        name="age_group_kind_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("max_years__isnull", True),
                            ("max_years__gte", models.F("min_years")),
                            _connector="OR",
                        ),
                        name="age_group_years_ordered",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="child",
            name="sabbath_class_override",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave empty and the birthday decides the Sabbath class.",
                limit_choices_to={"kind": "SABBATH"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="overridden_children",
                to="children.agegroup",
            ),
        ),
        migrations.RunPython(seed_age_groups, remove_age_groups),
    ]
