# Generated by Django 6.1.1 on 2026-10-04 18:20

from django.db import migrations, models

COLORS = {
    "baby-steps": "rose",
    "beginner": "amber",
    "kindergarten": "lime",
    "primary": "teal",
    "power-point": "blue",
    "realtime": "indigo",
    "corner-stone": "purple",
    "adventurer": "sky",
    "pathfinder": "orange",
}


def set_age_group_colors(apps, schema_editor):
    AgeGroup = apps.get_model("children", "AgeGroup")
    for slug, color in COLORS.items():
        AgeGroup.objects.filter(slug=slug).update(color=color)


class Migration(migrations.Migration):
    dependencies = [
        ("children", "0002_age_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="agegroup",
            name="color",
            field=models.CharField(
                choices=[
                    ("rose", "Rose"),
                    ("amber", "Amber"),
                    ("lime", "Green"),
                    ("teal", "Teal"),
                    ("blue", "Blue"),
                    ("indigo", "Indigo"),
                    ("purple", "Purple"),
                    ("sky", "Sky"),
                    ("orange", "Orange"),
                ],
                default="blue",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="agegroup",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "color__in",
                        [
                            "rose",
                            "amber",
                            "lime",
                            "teal",
                            "blue",
                            "indigo",
                            "purple",
                            "sky",
                            "orange",
                        ],
                    )
                ),
                name="age_group_color_valid",
            ),
        ),
        migrations.RunPython(set_age_group_colors, migrations.RunPython.noop),
    ]
