# Generated by Django 6.1.1 on 2026-10-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("children", "0003_age_group_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Optional. The child's own Ghana number, for example 024 412 3456.",
                max_length=20,
            ),
        ),
    ]
