# Generated by Django 6.1.1 on 2026-10-04 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("children", "0004_child_phone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="class_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PRESCHOOL", "Pre-school"),
                    ("BASIC_1", "Basic 1"),
                    ("BASIC_2", "Basic 2"),
                    ("BASIC_3", "Basic 3"),
                    ("BASIC_4", "Basic 4"),
                    ("BASIC_5", "Basic 5"),
                    ("BASIC_6", "Basic 6"),
                    ("JHS_1", "JHS 1"),
                    ("JHS_2", "JHS 2"),
                    ("JHS_3", "JHS 3"),
                    ("SHS_1", "SHS 1"),
                    ("SHS_2", "SHS 2"),
                    ("SHS_3", "SHS 3"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="child",
            name="school_name",
            field=models.CharField(
                blank=True, help_text="The school this child attends.", max_length=160
            ),
        ),
        migrations.AddIndex(
            model_name="child",
            index=models.Index(fields=["class_level"], name="children_ch_class_l_231f14_idx"),
        ),
        migrations.AddConstraint(
            model_name="child",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("class_level", ""),
                    (
                        "class_level__in",
                        [
                            "PRESCHOOL",
                            "BASIC_1",
                            "BASIC_2",
                            "BASIC_3",
                            "BASIC_4",
                            "BASIC_5",
                            "BASIC_6",
                            "JHS_1",
                            "JHS_2",
                            "JHS_3",
                            "SHS_1",
                            "SHS_2",
                            "SHS_3",
                        ],
                    ),
                    _connector="OR",
                ),
                name="child_class_level_valid",
            ),
        ),
    ]
