# Generated by Django 6.1.1 on 2026-10-03 07:30

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=20, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-start_date"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gte", models.F("start_date"))),
                        name="academic_year_dates_ordered",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("is_current",),
                        name="one_current_academic_year",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                (
                    "school_type",
                    models.CharField(
                        choices=[
                            ("BASIC", "Basic"),
                            ("PRIMARY", "Primary"),
                            ("JHS", "Junior high"),
                            ("SHS", "Senior high"),
                            ("OTHER", "Other"),
                        ],
                        default="BASIC",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=160)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"), name="school_unique_name_ci"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("school_type__in", ["BASIC", "PRIMARY", "JHS", "SHS", "OTHER"])
                        ),
                        name="school_type_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Optional sort order. Lower numbers appear first.",
                        null=True,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classes",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "class",
                "verbose_name_plural": "classes",
                "ordering": ["school__name", "level", "name"],
                "indexes": [
                    models.Index(fields=["school", "name"], name="schools_sch_school__703946_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        models.F("school"),
                        name="schoolclass_unique_name_per_school_ci",
                    )
                ],
            },
        ),
    ]
