# Generated by Django 6.1.1 on 2026-10-04 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("children", "0005_class_levels"),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassPlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_level",
                    models.CharField(
                        choices=[
                            ("PRESCHOOL", "Pre-school"),
                            ("BASIC_1", "Basic 1"),
                            ("BASIC_2", "Basic 2"),
                            ("BASIC_3", "Basic 3"),
                            ("BASIC_4", "Basic 4"),
                            ("BASIC_5", "Basic 5"),
                            ("BASIC_6", "Basic 6"),
                            ("JHS_1", "JHS 1"),
                            ("JHS_2", "JHS 2"),
                            ("JHS_3", "JHS 3"),
                            ("SHS_1", "SHS 1"),
                            ("SHS_2", "SHS 2"),
                            ("SHS_3", "SHS 3"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placements",
                        to="schools.academicyear",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_placements",
                        to="children.child",
                    ),
                ),
            ],
            options={
                "verbose_name": "class placement",
                "ordering": ["-academic_year__start_date"],
            },
        ),
        migrations.AddIndex(
            model_name="classplacement",
            index=models.Index(
                fields=["academic_year", "class_level"], name="schools_cla_academi_f442f5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="classplacement",
            constraint=models.UniqueConstraint(
                fields=("child", "academic_year"), name="one_class_placement_per_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="classplacement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "class_level__in",
                        [
                            "PRESCHOOL",
                            "BASIC_1",
                            "BASIC_2",
                            "BASIC_3",
                            "BASIC_4",
                            "BASIC_5",
                            "BASIC_6",
                            "JHS_1",
                            "JHS_2",
                            "JHS_3",
                            "SHS_1",
                            "SHS_2",
                            "SHS_3",
                        ],
                    )
                ),
                name="class_placement_level_valid",
            ),
        ),
    ]
